
version: 2.1

jobs:
  build_branch:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
      - run:
          name: Build
          command: |
            docker build \
              --tag szymonrychu/alpine-self-sign:$(echo $CIRCLE_SHA1 | cut -c -7) \
              .

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
      - run:
          name: Build
          command: |
            docker build \
              --tag szymonrychu/alpine-self-sign:$(echo $CIRCLE_SHA1 | cut -c -7) \
              .
      - run:
          name: Push
          command: |
            docker push szymonrychu/alpine-self-sign:$(echo $CIRCLE_SHA1 | cut -c -7)
  build_tag:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
      - run:
          name: Pull latest master-based container
          command: |
            docker pull szymonrychu/alpine-self-sign:$(echo $CIRCLE_SHA1 | cut -c -7)
      - run:
          name: Push
          command: |
            LATEST_TAG=$(git tag -l | sort --version-sort --field-separator=- | tail -1 | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')

            docker tag szymonrychu/alpine-self-sign:$(echo $CIRCLE_SHA1 | cut -c -7) szymonrychu/alpine-self-sign:latest
            docker tag szymonrychu/alpine-self-sign:latest szymonrychu/alpine-self-sign:${LATEST_TAG}
            docker push szymonrychu/alpine-self-sign:${LATEST_TAG}
            docker push szymonrychu/alpine-self-sign:latest
workflows:
  version: 2
  build:
    jobs:
      - build_branch:
          context: dockerhub
          filters:
            branches:
              ignore:
                - master
      - build:
          context: dockerhub
          filters:
            branches:
              only:
                - master
      - build_tag:
          context: dockerhub
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /.*/
